// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type ActivityHistory struct {
	ID             int64          `json:"id"`
	RecordID       sql.NullString `json:"record_id"`
	EmployeeID     string         `json:"employee_id"`
	EventID        string         `json:"event_id"`
	OccurredAt     string         `json:"occurred_at"`
	DueDate        sql.NullString `json:"due_date"`
	Status         string         `json:"status"`
	CompletionPct  int64          `json:"completion_pct"`
	Score          sql.NullInt64  `json:"score"`
	FeedbackRating sql.NullInt64  `json:"feedback_rating"`
	AssignedBy     string         `json:"assigned_by"`
	Source         string         `json:"source"`
	SourceKey      sql.NullString `json:"source_key"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
	CreatedAt      string         `json:"created_at"`
}

type DatasetMetadatum struct {
	Key       string `json:"key"`
	ValueJson string `json:"value_json"`
}

type Employee struct {
	ID                string         `json:"id"`
	FullName          string         `json:"full_name"`
	Department        string         `json:"department"`
	Role              string         `json:"role"`
	Grade             string         `json:"grade"`
	ManagerID         sql.NullString `json:"manager_id"`
	HireDate          string         `json:"hire_date"`
	TenureMonths      int64          `json:"tenure_months"`
	WorkFormat        string         `json:"work_format"`
	PreferredLanguage string         `json:"preferred_language"`
	CareerGoalRole    sql.NullString `json:"career_goal_role"`
	CareerGoalGrade   sql.NullString `json:"career_goal_grade"`
	LastReviewDate    string         `json:"last_review_date"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type EmployeeSkill struct {
	EmployeeID string `json:"employee_id"`
	SkillID    string `json:"skill_id"`
	Level      int64  `json:"level"`
	UpdatedAt  string `json:"updated_at"`
}

type Event struct {
	ID                   string         `json:"id"`
	TitleEn              string         `json:"title_en"`
	TitleRu              sql.NullString `json:"title_ru"`
	TitleKk              sql.NullString `json:"title_kk"`
	Description          string         `json:"description"`
	Type                 string         `json:"type"`
	Format               string         `json:"format"`
	DurationHours        float64        `json:"duration_hours"`
	Mandatory            int64          `json:"mandatory"`
	UpcomingSessionsJson string         `json:"upcoming_sessions_json"`
	Active               int64          `json:"active"`
}

type EventAudienceGrade struct {
	EventID string `json:"event_id"`
	Grade   string `json:"grade"`
}

type EventAudienceRole struct {
	EventID string `json:"event_id"`
	Role    string `json:"role"`
}

type EventPrerequisite struct {
	EventID       string `json:"event_id"`
	SkillID       string `json:"skill_id"`
	RequiredLevel int64  `json:"required_level"`
}

type EventSkillEffect struct {
	EventID  string `json:"event_id"`
	SkillID  string `json:"skill_id"`
	Gain     int64  `json:"gain"`
	MaxLevel int64  `json:"max_level"`
}

type GradeLevel struct {
	Role  string `json:"role"`
	Grade string `json:"grade"`
	Rank  int64  `json:"rank"`
}

type GradeRequirement struct {
	Role          string `json:"role"`
	Grade         string `json:"grade"`
	SkillID       string `json:"skill_id"`
	RequiredLevel int64  `json:"required_level"`
	Critical      int64  `json:"critical"`
}

type Skill struct {
	ID             string         `json:"id"`
	NameEn         string         `json:"name_en"`
	NameRu         sql.NullString `json:"name_ru"`
	NameKk         sql.NullString `json:"name_kk"`
	Category       string         `json:"category"`
	CategoryDetail string         `json:"category_detail"`
	Description    string         `json:"description"`
}
