// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type ActivityHistory struct {
	ID             int64          `json:"id"`
	EmployeeID     string         `json:"employee_id"`
	EventID        string         `json:"event_id"`
	OccurredAt     string         `json:"occurred_at"`
	Status         string         `json:"status"`
	Source         string         `json:"source"`
	SourceKey      sql.NullString `json:"source_key"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
	CreatedAt      string         `json:"created_at"`
}

type Employee struct {
	ID           string `json:"id"`
	Role         string `json:"role"`
	Grade        string `json:"grade"`
	TenureMonths int64  `json:"tenure_months"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type EmployeeSkill struct {
	EmployeeID string `json:"employee_id"`
	SkillID    string `json:"skill_id"`
	Level      int64  `json:"level"`
	UpdatedAt  string `json:"updated_at"`
}

type Event struct {
	ID      string         `json:"id"`
	TitleEn string         `json:"title_en"`
	TitleRu sql.NullString `json:"title_ru"`
	TitleKk sql.NullString `json:"title_kk"`
	Type    string         `json:"type"`
	Active  int64          `json:"active"`
}

type EventAudienceGrade struct {
	EventID string `json:"event_id"`
	Grade   string `json:"grade"`
}

type EventAudienceRole struct {
	EventID string `json:"event_id"`
	Role    string `json:"role"`
}

type EventSkillEffect struct {
	EventID  string `json:"event_id"`
	SkillID  string `json:"skill_id"`
	Gain     int64  `json:"gain"`
	MaxLevel int64  `json:"max_level"`
}

type GradeLevel struct {
	Role  string `json:"role"`
	Grade string `json:"grade"`
	Rank  int64  `json:"rank"`
}

type GradeRequirement struct {
	Role          string `json:"role"`
	Grade         string `json:"grade"`
	SkillID       string `json:"skill_id"`
	RequiredLevel int64  `json:"required_level"`
}

type Skill struct {
	ID       string         `json:"id"`
	NameEn   string         `json:"name_en"`
	NameRu   sql.NullString `json:"name_ru"`
	NameKk   sql.NullString `json:"name_kk"`
	Category string         `json:"category"`
}
