// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getEmployee = `-- name: GetEmployee :one
SELECT id, full_name, department, role, grade, tenure_months, preferred_language, career_goal_role, career_goal_grade, last_review_date FROM employees WHERE id = ?
`

type GetEmployeeRow struct {
	ID                string         `json:"id"`
	FullName          string         `json:"full_name"`
	Department        string         `json:"department"`
	Role              string         `json:"role"`
	Grade             string         `json:"grade"`
	TenureMonths      int64          `json:"tenure_months"`
	PreferredLanguage string         `json:"preferred_language"`
	CareerGoalRole    sql.NullString `json:"career_goal_role"`
	CareerGoalGrade   sql.NullString `json:"career_goal_grade"`
	LastReviewDate    string         `json:"last_review_date"`
}

func (q *Queries) GetEmployee(ctx context.Context, id string) (GetEmployeeRow, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Department,
		&i.Role,
		&i.Grade,
		&i.TenureMonths,
		&i.PreferredLanguage,
		&i.CareerGoalRole,
		&i.CareerGoalGrade,
		&i.LastReviewDate,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title_en, title_ru, title_kk, type, format, mandatory, upcoming_sessions_json, active FROM events WHERE id = ?
`

type GetEventRow struct {
	ID                   string         `json:"id"`
	TitleEn              string         `json:"title_en"`
	TitleRu              sql.NullString `json:"title_ru"`
	TitleKk              sql.NullString `json:"title_kk"`
	Type                 string         `json:"type"`
	Format               string         `json:"format"`
	Mandatory            int64          `json:"mandatory"`
	UpcomingSessionsJson string         `json:"upcoming_sessions_json"`
	Active               int64          `json:"active"`
}

func (q *Queries) GetEvent(ctx context.Context, id string) (GetEventRow, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.TitleEn,
		&i.TitleRu,
		&i.TitleKk,
		&i.Type,
		&i.Format,
		&i.Mandatory,
		&i.UpcomingSessionsJson,
		&i.Active,
	)
	return i, err
}

const getHistoryByIdempotencyKey = `-- name: GetHistoryByIdempotencyKey :one
SELECT id, employee_id, event_id, status FROM activity_history
WHERE employee_id = ? AND idempotency_key = ?
`

type GetHistoryByIdempotencyKeyParams struct {
	EmployeeID     string         `json:"employee_id"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
}

type GetHistoryByIdempotencyKeyRow struct {
	ID         int64  `json:"id"`
	EmployeeID string `json:"employee_id"`
	EventID    string `json:"event_id"`
	Status     string `json:"status"`
}

func (q *Queries) GetHistoryByIdempotencyKey(ctx context.Context, arg GetHistoryByIdempotencyKeyParams) (GetHistoryByIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getHistoryByIdempotencyKey, arg.EmployeeID, arg.IdempotencyKey)
	var i GetHistoryByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.EventID,
		&i.Status,
	)
	return i, err
}

const getNextGrade = `-- name: GetNextGrade :one
SELECT next.grade, next.rank FROM employees e
JOIN grade_levels current ON current.role = e.role AND current.grade = e.grade
JOIN grade_levels next ON next.role = current.role AND next.rank = current.rank + 1
WHERE e.id = ?
`

type GetNextGradeRow struct {
	Grade string `json:"grade"`
	Rank  int64  `json:"rank"`
}

func (q *Queries) GetNextGrade(ctx context.Context, id string) (GetNextGradeRow, error) {
	row := q.db.QueryRowContext(ctx, getNextGrade, id)
	var i GetNextGradeRow
	err := row.Scan(&i.Grade, &i.Rank)
	return i, err
}

const hRActivityParticipation = `-- name: HRActivityParticipation :many
SELECT e.id AS event_id, e.title_en,
       SUM(CASE WHEN h.status = 'completed' THEN 1 ELSE 0 END) AS completed,
       SUM(CASE WHEN h.status = 'no_show' THEN 1 ELSE 0 END) AS no_show,
       SUM(CASE WHEN h.status = 'dropped' THEN 1 ELSE 0 END) AS dropped,
       SUM(CASE WHEN h.status = 'declined' THEN 1 ELSE 0 END) AS declined,
       SUM(CASE WHEN h.status = 'in_progress' THEN 1 ELSE 0 END) AS in_progress,
       SUM(CASE WHEN h.status = 'overdue' THEN 1 ELSE 0 END) AS overdue
FROM events e LEFT JOIN activity_history h ON h.event_id = e.id
GROUP BY e.id ORDER BY completed DESC, e.id
`

type HRActivityParticipationRow struct {
	EventID    string          `json:"event_id"`
	TitleEn    string          `json:"title_en"`
	Completed  sql.NullFloat64 `json:"completed"`
	NoShow     sql.NullFloat64 `json:"no_show"`
	Dropped    sql.NullFloat64 `json:"dropped"`
	Declined   sql.NullFloat64 `json:"declined"`
	InProgress sql.NullFloat64 `json:"in_progress"`
	Overdue    sql.NullFloat64 `json:"overdue"`
}

func (q *Queries) HRActivityParticipation(ctx context.Context) ([]HRActivityParticipationRow, error) {
	rows, err := q.db.QueryContext(ctx, hRActivityParticipation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HRActivityParticipationRow
	for rows.Next() {
		var i HRActivityParticipationRow
		if err := rows.Scan(
			&i.EventID,
			&i.TitleEn,
			&i.Completed,
			&i.NoShow,
			&i.Dropped,
			&i.Declined,
			&i.InProgress,
			&i.Overdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hREmployeesWithoutStep = `-- name: HREmployeesWithoutStep :many
WITH targets AS (
  SELECT e.id AS employee_id, e.role, e.grade, next.grade AS target_grade
  FROM employees e
  JOIN grade_levels current ON current.role = e.role AND current.grade = e.grade
  JOIN grade_levels next ON next.role = e.role AND next.rank = current.rank + 1
)
SELECT t.employee_id
FROM targets t
WHERE NOT EXISTS (
  SELECT 1 FROM events ev
  JOIN event_skill_effects ef ON ef.event_id = ev.id
  JOIN grade_requirements r ON r.role = t.role AND r.grade = t.target_grade AND r.skill_id = ef.skill_id
  LEFT JOIN employee_skills es ON es.employee_id = t.employee_id AND es.skill_id = ef.skill_id
  WHERE ev.active = 1 AND ev.mandatory = 0
    AND MAX(COALESCE(es.level, 0), MIN(ef.max_level, COALESCE(es.level, 0) + ef.gain)) > COALESCE(es.level, 0)
    AND COALESCE(es.level, 0) < r.required_level
    AND (NOT EXISTS (SELECT 1 FROM event_audience_roles ar WHERE ar.event_id = ev.id)
         OR EXISTS (SELECT 1 FROM event_audience_roles ar WHERE ar.event_id = ev.id AND ar.role = t.role))
    AND (NOT EXISTS (SELECT 1 FROM event_audience_grades ag WHERE ag.event_id = ev.id)
         OR EXISTS (SELECT 1 FROM event_audience_grades ag WHERE ag.event_id = ev.id AND ag.grade = t.grade))
    AND NOT EXISTS (SELECT 1 FROM activity_history h
                    WHERE h.employee_id = t.employee_id AND h.event_id = ev.id AND h.status IN ('completed', 'in_progress', 'overdue'))
) ORDER BY t.employee_id
`

func (q *Queries) HREmployeesWithoutStep(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, hREmployeesWithoutStep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var employee_id string
		if err := rows.Scan(&employee_id); err != nil {
			return nil, err
		}
		items = append(items, employee_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hRSkillGaps = `-- name: HRSkillGaps :many
WITH targets AS (
  SELECT e.id AS employee_id, e.role, next.grade AS target_grade
  FROM employees e
  JOIN grade_levels current ON current.role = e.role AND current.grade = e.grade
  JOIN grade_levels next ON next.role = e.role AND next.rank = current.rank + 1
)
SELECT r.skill_id, s.name_en, s.name_ru, s.name_kk,
       COUNT(*) AS employees_below_target,
       SUM(r.required_level - COALESCE(es.level, 0)) AS total_missing_levels
FROM targets t
JOIN grade_requirements r ON r.role = t.role AND r.grade = t.target_grade
JOIN skills s ON s.id = r.skill_id
LEFT JOIN employee_skills es ON es.employee_id = t.employee_id AND es.skill_id = r.skill_id
WHERE COALESCE(es.level, 0) < r.required_level
GROUP BY r.skill_id ORDER BY employees_below_target DESC, total_missing_levels DESC, r.skill_id
`

type HRSkillGapsRow struct {
	SkillID              string          `json:"skill_id"`
	NameEn               string          `json:"name_en"`
	NameRu               sql.NullString  `json:"name_ru"`
	NameKk               sql.NullString  `json:"name_kk"`
	EmployeesBelowTarget int64           `json:"employees_below_target"`
	TotalMissingLevels   sql.NullFloat64 `json:"total_missing_levels"`
}

func (q *Queries) HRSkillGaps(ctx context.Context) ([]HRSkillGapsRow, error) {
	rows, err := q.db.QueryContext(ctx, hRSkillGaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HRSkillGapsRow
	for rows.Next() {
		var i HRSkillGapsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.NameEn,
			&i.NameRu,
			&i.NameKk,
			&i.EmployeesBelowTarget,
			&i.TotalMissingLevels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCompletedEvent = `-- name: HasCompletedEvent :one
SELECT EXISTS(SELECT 1 FROM activity_history
              WHERE employee_id = ? AND event_id = ? AND status = 'completed')
`

type HasCompletedEventParams struct {
	EmployeeID string `json:"employee_id"`
	EventID    string `json:"event_id"`
}

func (q *Queries) HasCompletedEvent(ctx context.Context, arg HasCompletedEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasCompletedEvent, arg.EmployeeID, arg.EventID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertCompletion = `-- name: InsertCompletion :one
INSERT INTO activity_history(employee_id, event_id, occurred_at, status, completion_pct, assigned_by, source, idempotency_key)
VALUES (?, ?, ?, 'completed', 100, 'app', 'app', ?) RETURNING id
`

type InsertCompletionParams struct {
	EmployeeID     string         `json:"employee_id"`
	EventID        string         `json:"event_id"`
	OccurredAt     string         `json:"occurred_at"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
}

func (q *Queries) InsertCompletion(ctx context.Context, arg InsertCompletionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCompletion,
		arg.EmployeeID,
		arg.EventID,
		arg.OccurredAt,
		arg.IdempotencyKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEligibleEvents = `-- name: ListEligibleEvents :many
SELECT e.id, e.title_en, e.title_ru, e.title_kk, e.type
FROM employees person JOIN events e ON e.active = 1 AND e.mandatory = 0
WHERE person.id = ?
  AND (NOT EXISTS (SELECT 1 FROM event_audience_roles ar WHERE ar.event_id = e.id)
       OR EXISTS (SELECT 1 FROM event_audience_roles ar WHERE ar.event_id = e.id AND ar.role = person.role))
  AND (NOT EXISTS (SELECT 1 FROM event_audience_grades ag WHERE ag.event_id = e.id)
       OR EXISTS (SELECT 1 FROM event_audience_grades ag WHERE ag.event_id = e.id AND ag.grade = person.grade))
  AND NOT EXISTS (SELECT 1 FROM activity_history h
                  WHERE h.employee_id = person.id AND h.event_id = e.id AND h.status IN ('completed', 'in_progress', 'overdue'))
  AND NOT EXISTS (SELECT 1 FROM event_prerequisites p
                  LEFT JOIN employee_skills ps ON ps.employee_id = person.id AND ps.skill_id = p.skill_id
                  WHERE p.event_id = e.id AND COALESCE(ps.level, 0) < p.required_level)
ORDER BY e.id
`

type ListEligibleEventsRow struct {
	ID      string         `json:"id"`
	TitleEn string         `json:"title_en"`
	TitleRu sql.NullString `json:"title_ru"`
	TitleKk sql.NullString `json:"title_kk"`
	Type    string         `json:"type"`
}

func (q *Queries) ListEligibleEvents(ctx context.Context, id string) ([]ListEligibleEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEligibleEvents, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleEventsRow
	for rows.Next() {
		var i ListEligibleEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleEn,
			&i.TitleRu,
			&i.TitleKk,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeHistory = `-- name: ListEmployeeHistory :many
SELECT h.id, h.event_id, e.title_en, e.title_ru, e.title_kk, e.type,
       h.occurred_at, h.due_date, h.status, h.completion_pct, h.assigned_by
FROM activity_history h JOIN events e ON e.id = h.event_id
WHERE h.employee_id = ? ORDER BY h.occurred_at DESC, h.id DESC
`

type ListEmployeeHistoryRow struct {
	ID            int64          `json:"id"`
	EventID       string         `json:"event_id"`
	TitleEn       string         `json:"title_en"`
	TitleRu       sql.NullString `json:"title_ru"`
	TitleKk       sql.NullString `json:"title_kk"`
	Type          string         `json:"type"`
	OccurredAt    string         `json:"occurred_at"`
	DueDate       sql.NullString `json:"due_date"`
	Status        string         `json:"status"`
	CompletionPct int64          `json:"completion_pct"`
	AssignedBy    string         `json:"assigned_by"`
}

func (q *Queries) ListEmployeeHistory(ctx context.Context, employeeID string) ([]ListEmployeeHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeHistory, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeHistoryRow
	for rows.Next() {
		var i ListEmployeeHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TitleEn,
			&i.TitleRu,
			&i.TitleKk,
			&i.Type,
			&i.OccurredAt,
			&i.DueDate,
			&i.Status,
			&i.CompletionPct,
			&i.AssignedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeSkills = `-- name: ListEmployeeSkills :many
SELECT es.skill_id, s.name_en, s.name_ru, s.name_kk, s.category, es.level
FROM employee_skills es JOIN skills s ON s.id = es.skill_id
WHERE es.employee_id = ? ORDER BY es.skill_id
`

type ListEmployeeSkillsRow struct {
	SkillID  string         `json:"skill_id"`
	NameEn   string         `json:"name_en"`
	NameRu   sql.NullString `json:"name_ru"`
	NameKk   sql.NullString `json:"name_kk"`
	Category string         `json:"category"`
	Level    int64          `json:"level"`
}

func (q *Queries) ListEmployeeSkills(ctx context.Context, employeeID string) ([]ListEmployeeSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeSkills, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeSkillsRow
	for rows.Next() {
		var i ListEmployeeSkillsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.NameEn,
			&i.NameRu,
			&i.NameKk,
			&i.Category,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventEffects = `-- name: ListEventEffects :many
SELECT ef.skill_id, ef.gain, ef.max_level, COALESCE(es.level, 0) AS current_level,
       MAX(COALESCE(es.level, 0), MIN(ef.max_level, COALESCE(es.level, 0) + ef.gain)) AS projected_level
FROM event_skill_effects ef
LEFT JOIN employee_skills es ON es.employee_id = ? AND es.skill_id = ef.skill_id
WHERE ef.event_id = ? ORDER BY ef.skill_id
`

type ListEventEffectsParams struct {
	EmployeeID string `json:"employee_id"`
	EventID    string `json:"event_id"`
}

type ListEventEffectsRow struct {
	SkillID        string      `json:"skill_id"`
	Gain           int64       `json:"gain"`
	MaxLevel       int64       `json:"max_level"`
	CurrentLevel   int64       `json:"current_level"`
	ProjectedLevel interface{} `json:"projected_level"`
}

func (q *Queries) ListEventEffects(ctx context.Context, arg ListEventEffectsParams) ([]ListEventEffectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventEffects, arg.EmployeeID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventEffectsRow
	for rows.Next() {
		var i ListEventEffectsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.Gain,
			&i.MaxLevel,
			&i.CurrentLevel,
			&i.ProjectedLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradeGaps = `-- name: ListGradeGaps :many
SELECT r.skill_id, s.name_en, s.name_ru, s.name_kk,
       r.required_level, r.critical, COALESCE(es.level, 0) AS current_level,
       MAX(0, r.required_level - COALESCE(es.level, 0)) AS gap
FROM grade_requirements r
JOIN skills s ON s.id = r.skill_id
JOIN employees e ON e.id = ? AND e.role = r.role
LEFT JOIN employee_skills es ON es.employee_id = e.id AND es.skill_id = r.skill_id
WHERE r.grade = ?
ORDER BY gap DESC, r.skill_id
`

type ListGradeGapsParams struct {
	ID    string `json:"id"`
	Grade string `json:"grade"`
}

type ListGradeGapsRow struct {
	SkillID       string         `json:"skill_id"`
	NameEn        string         `json:"name_en"`
	NameRu        sql.NullString `json:"name_ru"`
	NameKk        sql.NullString `json:"name_kk"`
	RequiredLevel int64          `json:"required_level"`
	Critical      int64          `json:"critical"`
	CurrentLevel  int64          `json:"current_level"`
	Gap           interface{}    `json:"gap"`
}

func (q *Queries) ListGradeGaps(ctx context.Context, arg ListGradeGapsParams) ([]ListGradeGapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGradeGaps, arg.ID, arg.Grade)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGradeGapsRow
	for rows.Next() {
		var i ListGradeGapsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.NameEn,
			&i.NameRu,
			&i.NameKk,
			&i.RequiredLevel,
			&i.Critical,
			&i.CurrentLevel,
			&i.Gap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryEvidence = `-- name: ListHistoryEvidence :many
SELECT h.id AS history_id, h.event_id, e.type, h.occurred_at, h.status, ef.skill_id
FROM activity_history h
JOIN events e ON e.id = h.event_id
JOIN event_skill_effects ef ON ef.event_id = e.id
WHERE h.employee_id = ?
ORDER BY h.occurred_at DESC, h.id DESC, ef.skill_id
`

type ListHistoryEvidenceRow struct {
	HistoryID  int64  `json:"history_id"`
	EventID    string `json:"event_id"`
	Type       string `json:"type"`
	OccurredAt string `json:"occurred_at"`
	Status     string `json:"status"`
	SkillID    string `json:"skill_id"`
}

func (q *Queries) ListHistoryEvidence(ctx context.Context, employeeID string) ([]ListHistoryEvidenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryEvidence, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHistoryEvidenceRow
	for rows.Next() {
		var i ListHistoryEvidenceRow
		if err := rows.Scan(
			&i.HistoryID,
			&i.EventID,
			&i.Type,
			&i.OccurredAt,
			&i.Status,
			&i.SkillID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const select1 = `-- name: Select1 :one
SELECT 1
`

func (q *Queries) Select1(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, select1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertEmployeeSkill = `-- name: UpsertEmployeeSkill :exec
INSERT INTO employee_skills(employee_id, skill_id, level)
VALUES (?, ?, ?)
ON CONFLICT(employee_id, skill_id) DO UPDATE SET
level = excluded.level, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertEmployeeSkillParams struct {
	EmployeeID string `json:"employee_id"`
	SkillID    string `json:"skill_id"`
	Level      int64  `json:"level"`
}

func (q *Queries) UpsertEmployeeSkill(ctx context.Context, arg UpsertEmployeeSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmployeeSkill, arg.EmployeeID, arg.SkillID, arg.Level)
	return err
}
