import employeesData from "@/data/employees.json";
import eventsData from "@/data/events.json";
import skillsData from "@/data/skills.json";
import historyData from "@/data/history.json";
import type { Employee, Event, Factor, Gap, History, ImportReport, Overview, Participation, Profile, RecResponse, Recommendation, RoleProfile, Skill } from "./types";

const EMPLOYEES = employeesData.employees as unknown as Employee[];
const EVENTS = eventsData.events as Event[];
const SKILLS = skillsData.skills as Skill[];
const PROFILES = skillsData.role_profiles as unknown as RoleProfile[];
const HISTORY = historyData as History[];
const grades = ["Junior", "Middle", "Senior", "Lead"];
const key = "career-quest-demo-v1";
type State = { employees:Employee[]; history:History[] };
function state():State { if (typeof window === "undefined") return {employees:[],history:[]}; try { return JSON.parse(localStorage.getItem(key) || '{"employees":[],"history":[]}') as State; } catch { return {employees:[],history:[]}; } }
function save(value:State) { localStorage.setItem(key, JSON.stringify(value)); }
export function allEmployees():Employee[] { const extra=state().employees; return [...EMPLOYEES.filter(e=>!extra.some(x=>x.employee_id===e.employee_id)),...extra].sort((a,b)=>a.employee_id.localeCompare(b.employee_id)); }
export function allHistory():History[] { return [...HISTORY,...state().history]; }
export const skillName=(id:string)=>SKILLS.find(s=>s.skill_id===id)?.name || id.replace(/^SK_/,"").replaceAll("_"," ");
const eventById=(id:string)=>EVENTS.find(e=>e.event_id===id);
export const eventTitle=(id:string)=>eventById(id)?.title||id;
function requirements(employee:Employee) { const index=grades.indexOf(employee.grade); const next=index>=0?grades[index+1] || null:null; const profile=PROFILES.find(p=>p.role===employee.role&&p.grade===next); return {next, profile}; }
function calcReadiness(skills:Record<string,number>, req:Record<string,number>) { const total=Object.values(req).reduce((a,b)=>a+b,0); return total?Object.entries(req).reduce((a,[id,r])=>a+Math.min(skills[id]||0,r),0)/total:0; }
function appliedSkills(employee:Employee, history:History[]) { const skills={...employee.skills}; history.filter(h=>h.status==="completed" && (h.record_id?.startsWith("demo-")||h.date>(employee.last_review_date||"9999"))).sort((a,b)=>a.date.localeCompare(b.date)).forEach(h=>eventById(h.event_id)?.develops_skills.forEach(effect=>{ const current=skills[effect.skill_id]||0; skills[effect.skill_id]=Math.max(current,Math.min(5,effect.max_level,current+effect.gain)); })); return skills; }
export function getProfile(id:string):Profile { const employee=allEmployees().find(e=>e.employee_id===id); if(!employee) throw new Error("Сотрудник не найден"); const history=allHistory().filter(h=>h.employee_id===id).sort((a,b)=>b.date.localeCompare(a.date)); const {next,profile}=requirements(employee); const skills=appliedSkills(employee,history); const gaps:Gap[]=Object.entries(profile?.required_skills||{}).map(([skill_id,required])=>({skill_id,name:skillName(skill_id),current:skills[skill_id]||0,required,gap:Math.max(0,required-(skills[skill_id]||0)),critical:!!profile?.critical_skills.includes(skill_id)})).sort((a,b)=>Number(b.critical)-Number(a.critical)||b.gap-a.gap); return {employee:{...employee,skills},next_grade:next,readiness_percent:profile?Math.round(calcReadiness(skills,profile.required_skills)*1000)/10:null,gaps,history}; }
function eligible(event:Event, profile:Profile) { const {employee,history}=profile; return !event.mandatory && (!event.target_roles.length||event.target_roles.includes(employee.role)) && (!event.target_grades.length||event.target_grades.includes(employee.grade)) && Object.entries(event.prerequisites||{}).every(([id,n])=>(employee.skills[id]||0)>=n) && (event.format==="self_paced"||event.upcoming_sessions?.some(date=>date>="2026-10-01")) && !history.some(h=>h.event_id===event.event_id&&h.status==="completed"); }
function effects(event:Event, profile:Profile) { return event.develops_skills.map(effect=>{const gap=profile.gaps.find(g=>g.skill_id===effect.skill_id); const from=profile.employee.skills[effect.skill_id]||0; const to=Math.max(from,Math.min(5,effect.max_level,from+effect.gain)); return {gap,from,to,closed:gap?Math.min(gap.required,to)-Math.min(gap.required,from):0}; }).filter(x=>x.closed>0); }
export function getRecommendations(id:string):RecResponse { const profile=getProfile(id); const current=(profile.readiness_percent||0)/100; if(!profile.next_grade) return {recommendations:[],readiness:{current,after_top:current},source:"fallback"};
  const rows=EVENTS.filter(e=>eligible(e,profile)).map(event=>{const gain=effects(event,profile); if(!gain.length)return null; const skillIds=new Set(event.develops_skills.map(s=>s.skill_id)); const similar=profile.history.filter(h=>eventById(h.event_id)?.develops_skills.some(s=>skillIds.has(s.skill_id)) && ["completed","skipped","declined","dropped","no_show"].includes(h.status)); const completed=similar.filter(h=>h.status==="completed").length; const missed=similar.length-completed; const engagement=(completed+1)/(similar.length+2); const gapClosed=gain.reduce((n,x)=>n+x.closed*(x.gap?.critical?2.5:1.5),0); const score=gapClosed*Math.pow(engagement,.7); return {event,gain,completed,missed,engagement,gapClosed,score}; }).filter((x):x is NonNullable<typeof x>=>!!x).sort((a,b)=>b.score-a.score).slice(0,3);
  const recommendations:Recommendation[]=rows.map(x=>{const primary=x.gain.sort((a,b)=>Number(b.gap?.critical)-Number(a.gap?.critical)||b.closed-a.closed)[0]; const gap=primary.gap!; const factors:Factor[]=[{type:"grade_requirement",text:`${gap.name} требуется для перехода на ${profile.next_grade}${gap.critical?" — ключевой навык":""}`,critical:gap.critical},{type:"skill_gap",skill:gap.skill_id,name:gap.name,current:gap.current,required:gap.required,text:`Сейчас ${gap.current} из ${gap.required}; разрыв ${gap.gap}`},{type:"history",completed:x.completed,total:x.completed+x.missed,missed:x.missed,text:x.completed+x.missed?`По похожим активностям: пройдено ${x.completed}, пропущено или отклонено ${x.missed}`:"Похожих активностей в истории пока нет"},...x.gain.map(g=>({type:"effective_gain" as const,skill:g.gap!.skill_id,name:g.gap!.name,from:g.from,to:g.to,text:`${g.gap!.name}: ${g.from} → ${g.to}`}))]; return {event_id:x.event.event_id,title:x.event.title,type:x.event.type,duration_hours:x.event.duration_hours,score:x.score,reason:`${gap.name}: сейчас ${gap.current} из ${gap.required} для ${profile.next_grade}. ${x.event.title} повысит уровень до ${primary.to}. ${x.completed+x.missed?`Из ${x.completed+x.missed} похожих активностей пройдено ${x.completed}.`:"Истории по похожим активностям пока нет."}`,reason_source:"template",factors,calculation:{gap_closed:x.gapClosed,engagement:x.engagement,formula:`${x.gapClosed.toFixed(2)} × ${x.engagement.toFixed(2)}^0.7`}}; });
  let afterTop=current; if(rows[0]){const skills={...profile.employee.skills}; rows[0].event.develops_skills.forEach(e=>skills[e.skill_id]=Math.max(skills[e.skill_id]||0,Math.min(5,e.max_level,(skills[e.skill_id]||0)+e.gain))); const req=PROFILES.find(p=>p.role===profile.employee.role&&p.grade===profile.next_grade)?.required_skills||{}; afterTop=calcReadiness(skills,req); }
  return {recommendations,readiness:{current,after_top:afterTop},source:"fallback"}; }
export function complete(id:string,eventId:string):Profile { const profile=getProfile(id); const event=eventById(eventId); if(!event||!eligible(event,profile))throw new Error("Активность недоступна или уже выполнена"); const current=state(); current.history.push({employee_id:id,event_id:eventId,date:new Date().toISOString().slice(0,10),status:"completed",record_id:`demo-${Date.now()}`}); save(current); return getProfile(id); }
export function getOverview():Overview { const employees=allEmployees(); const profiles=employees.map(e=>getProfile(e.employee_id)); const gapMap=new Map<string,{employee_count:number;missing_levels:number}>(); profiles.forEach(p=>p.gaps.filter(g=>g.gap>0).forEach(g=>{const v=gapMap.get(g.skill_id)||{employee_count:0,missing_levels:0};v.employee_count++;v.missing_levels+=g.gap;gapMap.set(g.skill_id,v);})); const weak_skills=[...gapMap].map(([skill_id,x])=>({skill_id,name:skillName(skill_id),...x})).sort((a,b)=>b.employee_count-a.employee_count).slice(0,10); const no_recommendation=profiles.filter(p=>p.next_grade&&!getRecommendations(p.employee.employee_id).recommendations.length).map(p=>({employee_id:p.employee.employee_id,full_name:p.employee.full_name,role:p.employee.role,grade:p.employee.grade,reason:"Нет подходящей активности для текущих разрывов"})); const all=allHistory(); const participation:Participation[]=EVENTS.map(e=>{const rows=all.filter(h=>h.event_id===e.event_id);const completed=rows.filter(h=>h.status==="completed").length;const skipped=rows.filter(h=>["skipped","no_show","dropped"].includes(h.status)).length;const declined=rows.filter(h=>h.status==="declined").length;return {event_id:e.event_id,title:e.title,completed,skipped,declined,completion_rate:completed+skipped+declined?Math.round(100*completed/(completed+skipped+declined)):0};}).filter(x=>x.completed+x.skipped+x.declined>0).sort((a,b)=>a.completion_rate-b.completion_rate); return {weak_skills,no_recommendation,participation,employee_count:employees.length,event_count:EVENTS.length}; }
export function importData(files:{employees?:File;history?:File}):Promise<ImportReport> { return Promise.all([files.employees?.text(),files.history?.text()]).then(([employeeText,historyText])=>{const current=state(); const report:ImportReport={imported:{employees:0,history:0},unchanged:{employees:0,history:0},errors:[]}; if(employeeText){const parsed=JSON.parse(employeeText); const rows:Employee[]=Array.isArray(parsed)?parsed:parsed.employees; if(!Array.isArray(rows))throw new Error("employees.json: нужен массив employees"); for(const [i,e] of rows.entries()){if(!e.employee_id||!e.role||!e.grade||!e.skills)throw new Error(`employees.json: запись ${i+1}: неполный профиль`); const existing=[...EMPLOYEES,...current.employees].find(x=>x.employee_id===e.employee_id); if(existing){if(JSON.stringify(existing)!==JSON.stringify(e))throw new Error(`employees.json: ${e.employee_id} уже существует с другими данными`);report.unchanged!.employees++;}else{current.employees.push(e);report.imported.employees++;}} }
    if(historyText){const lines=historyText.replace(/^\uFEFF/,"").trim().split(/\r?\n/); const header=lines.shift()?.split(",")||[]; for(const [i,line] of lines.entries()){const values=line.split(",");const row=Object.fromEntries(header.map((h,j)=>[h,values[j]||""])) as History;if(!row.employee_id||!row.event_id||!row.status)throw new Error(`activity_history.csv: строка ${i+2}: неполная запись`);if(![...EMPLOYEES,...current.employees].some(e=>e.employee_id===row.employee_id))throw new Error(`activity_history.csv: строка ${i+2}: неизвестный employee_id`);if(!eventById(row.event_id))throw new Error(`activity_history.csv: строка ${i+2}: неизвестный event_id`);if([...HISTORY,...current.history].some(h=>h.record_id&&h.record_id===row.record_id)){report.unchanged!.history++;}else{current.history.push(row);report.imported.history++;}} }
    save(current);return report; }); }
